#! /bin/sh
#
# Copyright (c) 2011-2013, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of Code Aurora Forum, Inc. nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# PM Configuration

set -e

case "$1" in
  start)
        soc_id=`cat /sys/devices/system/soc/soc0/id`
        case "$soc_id" in
        "104" | "105" | "106" | "107")
                echo -n "Starting powerconfig for 9x15: "
                echo 1 > /sys/module/pm_8x60/modes/cpu0/power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/standalone_power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/power_collapse/idle_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/standalone_power_collapse/idle_enabled
                echo 1 > /sys/module/rpm_resources/enable_low_power/pxo
                echo 2 > /sys/module/rpm_resources/enable_low_power/vdd_dig
                echo 2 > /sys/module/rpm_resources/enable_low_power/vdd_mem
                echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
                echo "done"
                ;;
         esac

         case "$soc_id" in
         "134" | "148" | "149" | "150" | "151" | "152" | "173" | "174" | "175")
                echo -n "Starting powerconfig for 9x25: "
                echo 1 > /sys/module/pm_8x60/modes/cpu0/power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/standalone_power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/power_collapse/idle_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/standalone_power_collapse/idle_enabled
                echo 1 > /sys/module/lpm_resources/enable_low_power/pxo
                echo 1 > /sys/module/lpm_resources/enable_low_power/vdd_dig
                echo 675000 > /sys/module/lpm_resources/enable_low_power/vdd_mem
                echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
                echo "done";
                ;;
         esac

         case "$soc_id" in
         "116" | "142")
                echo -n "Starting powerconfig for 8x30: "
                echo 1 > /sys/module/pm_8x60/modes/cpu0/power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu1/power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/standalone_power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu1/standalone_power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/standalone_power_collapse/idle_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu1/standalone_power_collapse/idle_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/power_collapse/idle_enabled
                echo 1 > /sys/module/rpm_resources/enable_low_power/L2_cache
                echo 1 > /sys/module/rpm_resources/enable_low_power/pxo
                echo 1 > /sys/module/rpm_resources/enable_low_power/vdd_dig
                echo 1 > /sys/module/rpm_resources/enable_low_power/vdd_mem
                echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
                echo ondemand > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
                chmod 664 /sys/devices/system/cpu/cpu1/online
                echo 10 > /sys/devices/platform/msm_sdcc.3/idle_timeout
                echo 50000 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
                echo 90 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
                echo 1 > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy
                echo 4 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
                echo 10 > /sys/devices/system/cpu/cpufreq/ondemand/down_differential
                echo 70 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_multi_core
                echo 918000 > /sys/devices/system/cpu/cpufreq/ondemand/optimal_freq
                echo 918000 > /sys/devices/system/cpu/cpufreq/ondemand/sync_freq
                echo 80 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_any_cpu_load
                echo 384000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
                echo 384000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
                echo "done"
                ;;
          esac
        ;;
  stop)
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage pm { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0

